SysIO::EndianWriter Class Reference
A stream object that is aware of the endianness of the system, and the endianness of the file being written. the stream can translate the data to any desired endianness as it writes the data.
#include <endian_writer.h>
Public Member Functions
EndianWriter (const std::string &, const ByteOrder &)
prepare a file for writing, and designate the endianness of the stream
~EndianWriter ()
Cleanup ofstream.
void seek (const size_t &)
Goto a specific offset.
void pad (const size_t &)
Treats n bytes as padding, skipping over them.
size_t tell ()
Gets the current position in the stream.
void writeString (const std::string &, const bool &=false)
Write a string to the stream. Null terminating if desired.
void writeRaw (const ByteArray &)
Write raw data to file from ByteArray (ByteArray is a vector<std::byte>)
template<class type >
void write (type data)
Write some data to file. Adjusted for endianness if required.
template<class type >
EndianWriter & operator<< (const type &data)
Write wrapper for << override.
template<class type >
void writeAt (const type &data, const size_t &offset)
Write some data to file at a specific offset. Adjusted for endianness if required (note stream position remains unchanged)
Private Attributes
std::ofstream file {}
Stream access to the file being written to.
ByteOrder fileEndianness {}
Endianness of the file, assigned at construction.
Static Private Attributes
static constexpr const char * EXCEPTION_FILE_ACCESS {`Unable To Access Requested File.`}
EXCEPTION_FILE_ACCESS - `Unable To Access Requested File.`.
Detailed Description
A stream object that is aware of the endianness of the system, and the endianness of the file being written. the stream can translate the data to any desired endianness as it writes the data.
Definition at line 19 of file endian_writer.h.
Constructor & Destructor Documentation
EndianWriter()
SysIO::EndianWriter::EndianWriter (const std::string & path, const ByteOrder & endianness)
prepare a file for writing, and designate the endianness of the stream
Parameters
std::string Path - File the stream is designated to write to
ByteOrder Endianness - Endianness of the file in question
Definition at line 10 of file endian_writer.cpp.
                                                                                 : fileEndianness(endianness)
    {
        file.open(path, std::ios_base::binary);
        if(!file.is_open())
            throw std::runtime_error(EXCEPTION_FILE_ACCESS);
    }
References EXCEPTION_FILE_ACCESS, and file.
 EndianWriter()
SysIO::EndianWriter::~EndianWriter ()
Cleanup ofstream.
Definition at line 17 of file endian_writer.cpp.
    {
        file.close();
    }
References file.
Member Function Documentation
operator<<()
template<class type >
EndianWriter& SysIO::EndianWriter::operator<< (const type & data) [inline]
Write wrapper for << override.
Parameters
type data - Data to write to file
Template Parameters
type - Template type
Definition at line 72 of file endian_writer.h.
        {
            // wrapper for write function
            write(data);
            return *this;
        }
References write().
pad()
void SysIO::EndianWriter::pad (const size_t & n)
Treats n bytes as padding, skipping over them.
Parameters
size_t n - Number of bytes as padding
Definition at line 27 of file endian_writer.cpp.
    {
        file.seekp(tell() + n);
    }
References file, and tell().
seek()
void SysIO::EndianWriter::seek (const size_t & offset)
Goto a specific offset.
Parameters
size_t Offset - Offset to the new stream position
Definition at line 22 of file endian_writer.cpp.
    {
        file.seekp(offset);
    }
References file.
Referenced by writeAt().
tell()
size_t SysIO::EndianWriter::tell ()
Gets the current position in the stream.
Returns
size_t - Stream position
Definition at line 32 of file endian_writer.cpp.
    {
        return file.tellp();
    }
References file.
Referenced by pad(), and writeAt().
write()
template<class type >
void SysIO::EndianWriter::write (type data) [inline]
Write some data to file. Adjusted for endianness if required.
Parameters
type data - Data to write to file
Template Parameters
type - Template type
Definition at line 60 of file endian_writer.h.
        {
            // swap the endianness if needed, then write the data
            if (SysIO::systemEndianness != fileEndianness)
                SysIO::EndianSwap(data);
            file.write(reinterpret_cast<char*>(&data), sizeof(type));
        }
References SysIO::EndianSwap(), file, fileEndianness, and SysIO::systemEndianness.
Referenced by operator<<(), and writeAt().
writeAt()
template<class type >
void SysIO::EndianWriter::writeAt (const type & data, const size_t & offset) [inline]
Write some data to file at a specific offset. Adjusted for endianness if required (note stream position remains unchanged)
Parameters
type data - Data to write to file
size_t offset - Offset to write the data at
Template Parameters
type - Template type
Definition at line 84 of file endian_writer.h.
        {
            // Store initial position, then seek to desired offset.
            const size_t initialPos {tell()};
            seek(offset);
            // write the data, and return to where we were at the start.
            write(data);
            seek(initialPos);
        }
References seek(), tell(), and write().
writeRaw()
void SysIO::EndianWriter::writeRaw (const ByteArray & raw)
Write raw data to file from ByteArray (ByteArray is a vector<std::byte>)
Parameters
ByteArray data - Raw data to write to file
Definition at line 44 of file endian_writer.cpp.
    {
        file.write(reinterpret_cast<const char*>(raw.data()), raw.size());
    }
References file.
writeString()
void SysIO::EndianWriter::writeString (const std::string & str, const bool & nullTerminated = false)
Write a string to the stream. Null terminating if desired.
Parameters
std::string str - String to write to the stream
bool nullTerminated - adds the null terminator to the end of the write
Definition at line 37 of file endian_writer.cpp.
    {
        file.write(str.data(), str.size());
        if(nullTerminated)
            file.write(new char{'\0'}, 1);
    }
References file.
Member Data Documentation
EXCEPTION_FILE_ACCESS
constexpr const char* SysIO::EndianWriter::EXCEPTION_FILE_ACCESS {`Unable To Access Requested File.`} [static], [constexpr], [private]
EXCEPTION_FILE_ACCESS - `Unable To Access Requested File.`.
Definition at line 23 of file endian_writer.h.
Referenced by EndianWriter().
file
std::ofstream SysIO::EndianWriter::file {} [private]
Stream access to the file being written to.
Definition at line 26 of file endian_writer.h.
Referenced by EndianWriter(), pad(), seek(), tell(), write(), writeRaw(), writeString(), and ~EndianWriter().
fileEndianness
ByteOrder SysIO::EndianWriter::fileEndianness {} [private]
Endianness of the file, assigned at construction.
Definition at line 28 of file endian_writer.h.
Referenced by write().
The documentation for this class was generated from the following files:
include/EndianStream/endian_writer.h
src/endian_writer.cpp