SysIO::EndianReader Class Reference
A stream object that is aware of the endianness of the system, and the endianness of the file being read. the stream can translate the data to the systems native endianness as it reads in the data.
#include <endian_reader.h>
Public Member Functions
EndianReader (const std::string &, const ByteOrder &)
Load a file, and designate the endianness of the stream.
~EndianReader ()
Cleanup ifstream.
void seek (const size_t &)
Goto a specific offset.
void pad (const size_t &)
Treats n bytes as padding, skipping over them.
size_t tell ()
Gets the current position in the stream.
std::string readString (const size_t &)
Read a fixed length string from the stream.
std::string readString ()
Read a null terminated string from the stream.
ByteArray readRaw (const size_t &, const size_t &)
Seek to an offset, read n bytes, and seek back original position.
ByteArray readRaw (const size_t &)
Read n bytes from current position.
template<class type >
type read ()
Read some data from the stream. Creates a new instance of type.
template<class type >
type peek ()
Read some data from the stream, without updating stream position. Creates a new instance of type.
template<class type >
EndianReader & operator>> (type &data)
Read some data from the stream into an existing object.
Public Attributes
size_t fileSize {}
Size of the file on disk.
std::ifstream file {}
Stream access to the file being read.
ByteOrder fileEndianness {}
Endianness of the file, assigned at construction.
Static Public Attributes
static constexpr const char * EXCEPTION_FILE_ACCESS {`Unable To Access Requested File.`}
EXCEPTION_FILE_ACCESS - `Unable To Access Requested File.`.
static constexpr const char * EXCEPTION_FILE_BOUNDS {`Requested Offset Exceeds Bounds Of The File.`}
EXCEPTION_FILE_BOUNDS - `Requested Offset Exceeds Bounds Of The File.`.
static const uint16_t MAXIMUM_STRING_LENGTH {0xffff}
MAXIMUM_STRING_LENGTH - 0xffff (65535)
Detailed Description
A stream object that is aware of the endianness of the system, and the endianness of the file being read. the stream can translate the data to the systems native endianness as it reads in the data.
Definition at line 20 of file endian_reader.h.
Constructor & Destructor Documentation
EndianReader()
SysIO::EndianReader::EndianReader (const std::string & path, const ByteOrder & endianness)
Load a file, and designate the endianness of the stream.
Parameters
std::string Path - File the stream is designated to read
ByteOrder Endianness - Endianness of the file in question
Definition at line 10 of file endian_reader.cpp.
                                                                                 : fileEndianness(endianness)
    {
        // Try and open file
        file.open(path, std::ios_base::in | std::ios_base::binary | std::ios_base::ate);
        if(!file.is_open())
            throw std::runtime_error(EXCEPTION_FILE_ACCESS);
        // Get the file size if successful.
        fileSize = file.tellg();
        file.seekg(0);
        return;
    }
References EXCEPTION_FILE_ACCESS, file, and fileSize.
 EndianReader()
SysIO::EndianReader::~EndianReader ()
Cleanup ifstream.
Definition at line 23 of file endian_reader.cpp.
    {
        // cleanup
        file.close();
    }
References file.
Member Function Documentation
operator>>()
template<class type >
EndianReader& SysIO::EndianReader::operator>> (type & data) [inline]
Read some data from the stream into an existing object.
Template Parameters
type - Template type
Parameters
data - Destination for the data read in from stream
Returns
EndianReader& - Returns it's self for chaining of >> operators
Definition at line 105 of file endian_reader.h.
        {
            // Read data from the stream, swap the endianness if needed.
            file.read(reinterpret_cast<char*>(&data), sizeof(data));
            if (SysIO::systemEndianness != fileEndianness)
                SysIO::EndianSwap(data);
            return *this;
        };
References SysIO::EndianSwap(), file, fileEndianness, and SysIO::systemEndianness.
pad()
void SysIO::EndianReader::pad (const size_t & n)
Treats n bytes as padding, skipping over them.
Parameters
size_t n - Number of bytes as padding
Definition at line 39 of file endian_reader.cpp.
    {
        // Skip over padding by seeking to the current position + padding size
        seek(tell() + n);
        return;
    }
References seek(), and tell().
peek()
template<class type >
type SysIO::EndianReader::peek () [inline]
Read some data from the stream, without updating stream position. Creates a new instance of type.
Template Parameters
type - Template Type
Returns
type - A new instance of 'type' read from the stream and adjusted for endianness
Definition at line 89 of file endian_reader.h.
        {
            // Read data of a certain type, seek the stream back, and return the data
            type ret;
            *this >> ret;
            seek(tell() - sizeof(type));
            return ret;
        }
References seek(), and tell().
read()
template<class type >
type SysIO::EndianReader::read () [inline]
Read some data from the stream. Creates a new instance of type.
Template Parameters
type - Template type
Returns
type - A new instance of 'type' read from the stream and adjusted for endianness
Definition at line 77 of file endian_reader.h.
        {
            // Read data of a certain type and return it.
            type ret;
            *this >> ret;
            return ret;
        }
readRaw() [1/2]
ByteArray SysIO::EndianReader::readRaw (const size_t & n)
Read n bytes from current position.
Parameters
size_t n - Number for bytes to read
Returns
ByteArray - Range of bytes requested
Definition at line 98 of file endian_reader.cpp.
    {
        // If the end of the block exceeds the file size, we'll end up with an overflow.
        if(tell() + n > fileSize)
            throw std::runtime_error(EXCEPTION_FILE_BOUNDS);
        // Create a ByteArray of 'size' width. Read from the file into byte array
        ByteArray ret(n);
        file.read(reinterpret_cast<char*>(ret.data()), n);
        return ret;
    }
References EXCEPTION_FILE_BOUNDS, file, fileSize, and tell().
readRaw() [2/2]
ByteArray SysIO::EndianReader::readRaw (const size_t & offset, const size_t & n)
Seek to an offset, read n bytes, and seek back original position.
Parameters
size_t offset - Offset to start read from
size_t n - Number of bytes to read
Returns
ByteArray - Range of bytes requested
Definition at line 80 of file endian_reader.cpp.
    {
        // Store the original position, and create a vector<byte> of the right size
        const size_t initPos { tell() };
        ByteArray ret(n);
        // If the end of the block exceeds the file size, we'll end up with an overflow.
        if(offset + n > fileSize)
            throw std::runtime_error(EXCEPTION_FILE_BOUNDS);
        // Seek to the beginning of the data, Read the data, then return to initPos
        seek(offset);
        file.read(reinterpret_cast<char*>(ret.data()), n);
        seek(initPos);
        return ret;
    }
References EXCEPTION_FILE_BOUNDS, file, fileSize, seek(), and tell().
readString() [1/2]
std::string SysIO::EndianReader::readString ()
Read a null terminated string from the stream.
Returns
std::string - String read from stream
Definition at line 62 of file endian_reader.cpp.
    {
        std::string ret;
        char buffer;
        // For loop prevents infinite loop
        for(size_t i = 0; i < MAXIMUM_STRING_LENGTH; ++i)
        {
            // Read a char at a time until we reach a null terminator.
            file.read(&buffer, 1);
            if(buffer == '\0')
                break;
            ret.push_back(buffer);
        };
        return ret;
    }
References file, and MAXIMUM_STRING_LENGTH.
readString() [2/2]
std::string SysIO::EndianReader::readString (const size_t & size)
Read a fixed length string from the stream.
Parameters
size_t size - Size of the string
Returns
std::string - String read from stream
Definition at line 52 of file endian_reader.cpp.
    {
        // Create a string large enough to hold the data.
        std::string ret(size, '\0');
        // Read into, and return the string.
        file.read(ret.data(), size);
        return ret;
    }
References file.
seek()
void SysIO::EndianReader::seek (const size_t & offset)
Goto a specific offset.
Parameters
size_t Offset - Offset to the new stream position
Definition at line 29 of file endian_reader.cpp.
    {
        // If requested offset exceeds the bounds of the file size. something is wrong.
        if(offset > fileSize)
            throw std::runtime_error(EXCEPTION_FILE_BOUNDS);
        // If not seek and return;
        file.seekg(offset);
        return;
    }
References EXCEPTION_FILE_BOUNDS, file, and fileSize.
Referenced by pad(), peek(), and readRaw().
tell()
size_t SysIO::EndianReader::tell ()
Gets the current position in the stream.
Returns
size_t - Stream position
Definition at line 46 of file endian_reader.cpp.
    {
        // Return the current position in the ifstream
        return file.tellg();
    }
References file.
Referenced by pad(), peek(), and readRaw().
Member Data Documentation
EXCEPTION_FILE_ACCESS
constexpr const char* SysIO::EndianReader::EXCEPTION_FILE_ACCESS {`Unable To Access Requested File.`} [static], [constexpr]
EXCEPTION_FILE_ACCESS - `Unable To Access Requested File.`.
Definition at line 24 of file endian_reader.h.
Referenced by EndianReader().
EXCEPTION_FILE_BOUNDS
constexpr const char* SysIO::EndianReader::EXCEPTION_FILE_BOUNDS {`Requested Offset Exceeds Bounds Of The File.`} [static], [constexpr]
EXCEPTION_FILE_BOUNDS - `Requested Offset Exceeds Bounds Of The File.`.
Definition at line 26 of file endian_reader.h.
Referenced by readRaw(), and seek().
file
std::ifstream SysIO::EndianReader::file {}
Stream access to the file being read.
Definition at line 33 of file endian_reader.h.
Referenced by EndianReader(), operator>>(), readRaw(), readString(), seek(), tell(), and ~EndianReader().
fileEndianness
ByteOrder SysIO::EndianReader::fileEndianness {}
Endianness of the file, assigned at construction.
Definition at line 35 of file endian_reader.h.
Referenced by operator>>().
fileSize
size_t SysIO::EndianReader::fileSize {}
Size of the file on disk.
Definition at line 31 of file endian_reader.h.
Referenced by EndianReader(), readRaw(), and seek().
MAXIMUM_STRING_LENGTH
const uint16_t SysIO::EndianReader::MAXIMUM_STRING_LENGTH {0xffff} [static]
MAXIMUM_STRING_LENGTH - 0xffff (65535)
Definition at line 28 of file endian_reader.h.
Referenced by readString().
The documentation for this class was generated from the following files:
include/EndianStream/endian_reader.h
src/endian_reader.cpp