.TH "include/EndianStream/endian_reader.h" 3 "Sat Jun 19 2021" "Version 1.0" "Endian Stream" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/EndianStream/endian_reader.h
.SH SYNOPSIS
.br
.PP
\fC#include 'sys_io\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSysIO::EndianReader\fP"
.br
.RI "A stream object that is aware of the endianness of the system, and the endianness of the file being read\&. the stream can translate the data to the systems native endianness as it reads in the data\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSysIO\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Endian Stream from the source code\&.
