.TH "endian_reader.cpp" 3 "Sat Jun 19 2021" "Version 1.0" "Endian Stream" \" -*- nroff -*-
.ad l
.nh
.SH NAME
endian_reader.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/EndianStream/endian_reader\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSysIO\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Endian Stream from the source code\&.
