.TH "include/EndianStream/endian_writer.h" 3 "Sat Jun 19 2021" "Version 1.0" "Endian Stream" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/EndianStream/endian_writer.h
.SH SYNOPSIS
.br
.PP
\fC#include 'sys_io\&.h'\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <exception>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSysIO::EndianWriter\fP"
.br
.RI "A stream object that is aware of the endianness of the system, and the endianness of the file being written\&. the stream can translate the data to any desired endianness as it writes the data\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSysIO\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Endian Stream from the source code\&.
