.TH "include/EStream.h" 3 "Sat Jun 19 2021" "Version 1.0" "Endian Stream" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/EStream.h
.SH SYNOPSIS
.br
.PP
\fC#include 'EndianStream\\endian_reader\&.h'\fP
.br
\fC#include 'EndianStream\\endian_writer\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENDIANSTREAM_VERSION_MAJOR\fP   @ENDIANSTREAM_VERSION_MAJOR@"
.br
.ti -1c
.RI "#define \fBENDIANSTREAM_VERSION_MINOR\fP   @ENDIANSTREAM_VERSION_MINOR@"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENDIANSTREAM_VERSION_MAJOR   @ENDIANSTREAM_VERSION_MAJOR@"

.PP
Definition at line 9 of file EStream\&.h\&.
.SS "#define ENDIANSTREAM_VERSION_MINOR   @ENDIANSTREAM_VERSION_MINOR@"

.PP
Definition at line 10 of file EStream\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Endian Stream from the source code\&.
