.TH "sys_io.cpp" 3 "Sat Jun 19 2021" "Version 1.0" "Endian Stream" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sys_io.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'include/EndianStream/sys_io\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBSysIO\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "ByteOrder \fBSysIO::getSystemEndianness\fP ()"
.br
.RI "Determines system endianness\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Endian Stream from the source code\&.
